[build]
  command = "cd web && npm install && npm run build"
  publish = "web/.next"

[build.environment]
  NODE_VERSION = "18"

[[redirects]]
  from = "/api/*"
  to = "http://127.0.0.1:8000/api/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200